default_platform(:ios)

platform :ios do

  def get_api_key
    app_store_connect_api_key(
      key_id: "WNSMV275TJ",
      issuer_id: "3962a192-f45e-4534-b559-6216d50a9136",
      key_filepath: File.expand_path("../AuthKey_WNSMV275TJ.p8", __dir__),
      duration: 1200,
      in_house: false
    )
  end

  def build_and_sign(api_key)
    current_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.jam.un4seen.app"
    )
    increment_build_number(
      build_number: current_build + 1,
      xcodeproj: "Runner.xcodeproj"
    )
    match(type: "appstore", readonly: true, api_key: api_key)
    sh("cd ../.. && flutter build ios --release --no-codesign")
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "un4seen.ipa"
    )
  end

  desc "TestFlight Beta"
  lane :beta do
    api_key = get_api_key
    build_and_sign(api_key)
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "App Store Production"
  lane :production do
    api_key = get_api_key
    build_and_sign(api_key)
    upload_to_app_store(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      precheck_include_in_app_purchases: false
    )
  end

end
