default_platform(:android)

platform :android do

  def get_next_build_number(track_name)
    begin
      last_build = google_play_track_version_codes(
        track: track_name,
        package_name: 'com.jam.un4seen.app'
      ).max
      return last_build + 1
    rescue
      return 1
    end
  end

  desc "Internal Testing"
  lane :internal do
    new_build_num = get_next_build_number('internal')
    sh("cd .. && flutter build appbundle --release --build-number=#{new_build_num}")
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Production (Live)"
  lane :production do
    new_build_num = get_next_build_number('production')
    sh("cd .. && flutter build appbundle --release --build-number=#{new_build_num}")
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      rollout: '1.0'
    )
  end

  desc "Internal → Production promote"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'production',
      rollout: '1.0'
    )
  end

end